### ISSUE TITLE
Do I need to apply this fix if I install the Convenience Update

### ISSUE THREAD

**Issue by RadarNyan** [aakkam22/windowsUpdateLoopFix#1]
I found this fix from the link here:

https://answers.microsoft.com/en-us/windows/forum/windows_7-update/fix-windows-7-update-stuck-on-checking-for-updates/ad6cfeef-232a-49b4-a57b-39978eea6630?tm=1502469047658

And I noticed another article by you about the "Convenience Update"

https://answers.microsoft.com/en-us/windows/forum/windows_7-update/how-to-obtain-and-install-windows-7-sp2/c2c7009f-3a10-4199-9c89-48e1e883051e

So I need to do a fresh install of Windows 7 SP1 x64, should I apply this fix first or the Convenience Update would cover it?

**Comment by aakkam22** [comment]
You should apply the fix first and then the convenience update. The fix is like a primer.
