### ISSUE TITLE
"Download Failed" For Downloading KB3020369 and KB3172605 updates

### ISSUE THREAD

**Issue by web5x** [aakkam22/windowsUpdateLoopFix#10]
The script no longer downloads the KB3020369 and KB3172605 updates, I had to download them manually from https://www.catalog.update.microsoft.com/ . (Possibly related to #9?)

**Comment by HorlogeSkynet** [comment]
Hello @aakkam22, are you still there to look into this ? :innocent:

**Comment by aakkam22** [comment]
Hi @web5x I just tested the URLs for all both the 32 and 64-bit KBs and the WUA and all download fine. I also tried using bitsadmin in the command prompt and no issues. Can you check if you have any antivirus software that might be deleting them once they get downloaded?

**Comment by HorlogeSkynet** [comment]
Closing due to stale, feel free to re-open if needed @web5x :pray:
