### ISSUE TITLE
Just look whats is telling 

### ISSUE THREAD

**Issue by MuduZunu** [aakkam22/windowsUpdateLoopFix#11]
![l](https://github.com/user-attachments/assets/454e0eb9-ab07-42d8-8fe0-582688ac8da9)

**Comment by HorlogeSkynet** [comment]
Hello @MuduZunu, have you tried again "later" ?

**Comment by aakkam22** [comment]
Check your Internet connection and firewall settings, the URLs in the script are active. If the files are being deleted by the local antivirus or the Internet connection is blocking the downloads, then that is out of my control,
