### ISSUE TITLE
Code 80080005

### ISSUE THREAD

**Issue by koning201** [aakkam22/windowsUpdateLoopFix#3]
The script ran fine, but I received error code 5 when the update utility was being installed. The KB updates all downloaded effectively, but when installing, it stated they were already there. When I attempted to search for updates through windows update, it searched for a few minutes then responded with a Code 80080005. Any ideas? This was the same problem I was running into before I ran the windowsUpdateLoopFix. Thanks!

**Comment by aakkam22** [comment]
Errors ending in 0005 are often "Access is Denied" errors. These are the hardest errors to diagnose and usually indicate a corruption somewhere. Forewarning that this error is not easily solved.

Could you elaborate further on the error code 5 that you received? At what point specifically in the installation did you receive it? Also, to clarify, **all three** patches were reported as already installed, correct?

Please open an elevated command prompt and run the following commands:

* sfc /scannow
* chkdsk /r (this command will require a reboot)

Report back the results. If the error persists, please zip and upload the the logs located at:

* C:\Windows\Windowsupdate.log 
* C:\Logs\CBS\CBS.log

Thanks!
