### ISSUE TITLE
Wizard.exe tries to run start.bat

### ISSUE THREAD

**Issue by gdstuart** [aakkam22/windowsUpdateLoopFix#4]
I followed all your instructions but when I double-click Wizard.exe, it displays a dialog that tells me that start.bat has no association in Windows.  What do I do with start.bat?

**Comment by aakkam22** [comment]
Your computer doesn't know what program is associated with .bat files. Possibly some program damaged the associations.

To restore them you'll need to delete the UserChoice key under the following registry location:

**Comment by gdstuart** [comment]
That key (FileExts.bat) doesn't exist in my Registry.  How do I create it?

**Comment by gdstuart** [comment]
Not so fast, as the saying goes.

Everything was working fine, so I started Windows Update and selected all the Critical Updates that applied to my situation and they were successfully applied.  But then Windows Update said I had a bunch more Critical Updates, so I went back in and found they were all Language Packs and updates for software I don't have like PowerPoint, so I did not select any of them.  

Then I noticed a bunch of Optional Updates that sounded important, so I chose a few of them to apply.  During the update process, I got a BSOD, so I restarted and got booted up, but now my mouse is again non-functional.  My next step was to go to System Restore to restore back to the Restore Point generated by your Wizard, but of course the BSOD or some other fluke wiped out all of my Restore Points prior to the one created by the WinUpdate that caused the BSOD.  So there's Point to restore from.

It's a Logitech M335 Wireless Mouse.  How can I force the driver to re-install?  Or is there something else I can try to fully remove this mouse and re-install it?  

And why do my Restore Points often disappear?  Is this some cruel trick by Microsoft to delete Restore Points just when I need them to be there?  I have checked the recommended settings for System Restore and they are all properly set up.

Thanks,

Geoff

**Comment by aakkam22** [comment]
Hi Geoff, 

There are several red flags in your earlier comments. 

You stated earlier that you installed KB4074588. As far as I can see, that is a Windows 10 update not a Windows 7 update. If you're running Windows 10 this fix isn't designed for your system. Please confirm your OS.

The registry key located at HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\ is an important registry key that your computer can't function without. You stated earlier that it was missing entirely. This indicates a serious corruption within Windows. 

Your mouse is plug and play. That means Windows automatically detects your hardware and installs the built-in drivers. First check that the hardware is functional by testing it on another computer. You can also try to uninstall the mouse from Device Manager and reboot to let Windows reinstall it. If that doesn't work then there is likely a bigger problem quite possibly related to the missing registry key from earlier. 

Restore points can disappear for a few reasons:

- You run out of space on your hard drive
- You toggle system restore on or off (software can do this too, the wizard does not interfere with this)
- You don't allocate enough room for use by system restore, in which case Windows will delete the oldest ones to make room for the newest ones (you can adjust allocation by going to **System Properties > Advanced System Settings > System Protection tab > Configure**)
- Restore points older than 90 days are automatically deleted

Sorry for the long post, just a lot to address :)

**Comment by gdstuart** [comment]
First off, allow me to thank you for your attention to this problem and your detailed assistance.  Not often do I encounter timely and skilled help on an open support forum.

Your comments deserve some explanation, so here goes.

I was referred to KB4074588 on the Microsoft forum.  Evidently I failed to note that it was for Win10.  It did not fix the mouse issue, but also didn't (overtly) break anything, so I moved on to the recommended Registry fix from Tweaking.com (more below on that).

My comment about not finding HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.bat was accurate, but you inferred that the whole HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\ key was missing.  That is incorrect.  It was present, but the ".bat" and ".cmd" keys were not, so that explains why I got the error when I dbl-clicked on your wizard.bat.  When I ran the Tweaking.com Registry fixer, I concentrated on the area that fixes file associations.  After running that fix, I checked the Registry and found .bat and .cmd, and the Wizard executed.  I did choose the option at the conclusion of your script to create a System Restore point, which later on was not present.  I am aware of the several steps I need to take to make sure SRP's don't disappear, and will do that later today.  Plus, I re-ran this tool later in the day with more options checked, and perhaps that cleaned up any issues that the install of KB4074588 may have introduced.  Just a guess...

Your advice about the PnP mouse was spot-on.  I opened Device Mgr and deleted three mice (two HID-Compliant and one PS/2-Compatible), did two reboots as requested, and the M355 mouse is working again.

I am left with two questions:

1.  In Dev Mgr, I like to keep everything running and clean.  For a long time I have noticed that the Microsoft Teredo Tunneling Adapter is flagged with a Code 10 (Driver will not start).  I deleted it and rebooted, and it did not come back, so right now Dev Mgr is clean.  What is this driver and is it important that I fix it?

2.  Should I install Win7 Service Pack 2 or just be happy that everything is currently running (if it ain't broke...)?

Again, thanks for your assistance.  I just turned 67 so this proves that you actually can teach an old dog some new tricks.

Geoff

**Comment by gdstuart** [comment]
Can we re-open this thread?  I faithfully trusted WinUpdate, installed KB4100480, rebooted, and the mouse is not working.  I deinstalled it, rebooted, reinstalled it, rebooted, and still no go.   My backup is a crummy, logo freebie mouse someone gave me and it works fine, but I hate the action.  Ditto for my old wired mouse.

If the Logitech M335 Wireless Mouse truly is PnP, why is my PC having so much difficulty with it?

**Comment by aakkam22** [comment]
Hi,

I would suggest you open a thread on SevenForums to get your question answered as your question is now outside the scope of this forum. 

Thanks for your understanding :)
