### ISSUE TITLE
stuck on "requesting for administrative privileges"

### ISSUE THREAD

**Issue by samuelburns62** [aakkam22/windowsUpdateLoopFix#5]
I ran the script and everything seemed to be working until this  message poped up. It has been more than an hour. Should i kill the process?

**Comment by samuelburns62** [comment]
Thanks for the virus assholes!

**Comment by HorlogeSkynet** [comment]
Hi, I do think you should edit or remove your latest comment as this "thought" is already addressed within the README and in #3.
Ain't time for that childishness.

**Comment by aakkam22** [comment]
samuelburns62 I suggest that you reopen the wizard and use the advanced options to skip to the section where it left off. Batch script processing sometimes gets stuck and I will research this particular issue. Thank you for letting me know.
