### ISSUE TITLE
Hangs/stuck on Downloading Windows Update Agent v7.6

### ISSUE THREAD

**Issue by TiniChrissy** [aakkam22/windowsUpdateLoopFix#6]
As the title says, the download seems to either be super slow or stuck. The other updates (KB3020369) and (KB3172605) downloaded quickly.

**Comment by aakkam22** [comment]
Hi, did you let the tool run completely and then let Windows Update check for updates? The first time might take a while depending on your Internet speed and computer settings - 30 to 60 minutes.

**Comment by TiniChrissy** [comment]
Hi sorry about the bad quality photos, but the laptop I am doing this on cannot access normal web browsing (but it should have normal internet access). I have let it wait for over 60 minutes and it still did not download. 

Normally when it hangs it looks like this. 
![signal-2021-03-13-125210_001](https://user-images.githubusercontent.com/17568055/111015114-5ae63b80-83fb-11eb-8552-4e0be90d103b.jpeg)

After trying to run windows update through the normal way, I got error code 8007000E, and I don't know if it's a coincidence or not but I got this screen when I tried to run the express install again. 
![signal-2021-03-13-125210_002](https://user-images.githubusercontent.com/17568055/111015146-7c472780-83fb-11eb-9943-aff326154740.jpeg)

**Comment by aakkam22** [comment]
Hi, thank you for the photos, they really help in troubleshooting. Can you run the tool again and when you get the error 'one or more of the files could not be downloaded', do not close the window - instead go to the folder C:\packages and can you take a screenshot of its contents?

Thanks

**Comment by TiniChrissy** [comment]
Hi sorry I had gotten busy with other things and left this. I think the issue solved itself after restarting a few times.

**Comment by aakkam22** [comment]
Hi, good to hear, let me know if you have another issue.
