### ISSUE TITLE
Missing check for packages folder

### ISSUE THREAD

**Issue by b8engl** [aakkam22/windowsUpdateLoopFix#7]
Something like

if not exist "c:\packages\" mkdir "c:\packages\"

**Comment by aakkam22** [comment]
Screenshot please

**Comment by b8engl** [comment]
buddy, your .tmp files aren't downloading if packages folder isn't created.

**Comment by aakkam22** [comment]
There is no such syntax, can you be more specific about what the problem is?

**Comment by b8engl** [comment]
Missing check for packages folder -> buddy, your .tmp files aren't downloading if packages folder isn't created.

**Comment by b8engl** [comment]
don't know why you asking for screenshot or be more specific as I did in title, but anyway...

Used option "Express Fix (Recommended)"
stuck in download process...
I check In c:\ for packages folder
missing folder!
ctrl + shift n = create folder packages
done!

**Comment by aakkam22** [comment]
This is done by calling the initializeDownload function

**Comment by aakkam22** [comment]
I have tested and it works successfully

**Comment by b8engl** [comment]
Maybe md faild on line 150

**Comment by b8engl** [comment]
> I have tested and it works successfully

Ok, but didn't work here

**Comment by aakkam22** [comment]
Are you running as administrator by downloading the tool from the releases section? Won't work correctly if you download the raw script

**Comment by b8engl** [comment]
mkdir would be 

> Are you running as administrator by downloading the tool from the releases section? Won't work correctly if you download the raw script

I'm done!

**Comment by aakkam22** [comment]
md and mkdir are the same command. You can change it if you want and try

**Comment by b8engl** [comment]
I didn't do any clone, why you go in other direction.
Use mkdir instead!

**Comment by aakkam22** [comment]
Right, I will look into this and see if I can replicate the issue. For now, are you able to workaround by creating the packages folder manually?

**Comment by b8engl** [comment]
`if exist %systemdrive%\packages ( rmdir %systemdrive%\packages /s /q > nul && mkdir %systemdrive%\packages > nul ) else ( mkdir %systemdrive%\packages > nul )`

**Comment by b8engl** [comment]
No need for ` 2>&1`
