### ISSUE TITLE
Broken download link for Windows Update Agent v7.6

### ISSUE THREAD

**Issue by mahatma-panda** [aakkam22/windowsUpdateLoopFix#8]
https://github.com/aakkam22/windowsUpdateLoopFix/blob/f9a2f5ed219291ded44a0402a7872979ea7d7fb2/master.cmd#L183

This link appears to be broken. The script hangs on this line since the link is dead. 

There is an archive of the link from archive.org at the following URL: https://web.archive.org/web/20220206050819/http://download.windowsupdate.com/windowsupdate/redist/standalone/7.6.7600.320/windowsupdateagent-7.6-x64.exe

I did not verify the authenticity of the archive.org file.

**Comment by HorlogeSkynet** [comment]
Hi @mahatma-panda, the link seems to "work for me". Could you try again ?
Thanks, bye :bow:

**Comment by aakkam22** [comment]
@mahatma-panda Link works for me if inserted in web browser, but I will investigate to see if I can reproduce the issue. Thanks

**Comment by mahatma-panda** [comment]
I tried the link (not the script) from a different machine and it worked fine. I have no idea what happened. I'll troubleshoot some more on the affected machine.

**Comment by mahatma-panda** [comment]
I am back at this again. 

I am digging a bit further into this. Two things:

1. It appears that for some reason, WindowsUpdateAgent will not download through CMD. (I am able to download it through chrome.) 
2. The error being thrown by BITSADMIN does not appear to be handled correctly by the script. It appears to hang indefinitely on "Downloading Windows Update Agent v7.6..."

Below is the output when I run the following command in an admin cmd:
`bitsadmin /transfer wua http://download.windowsupdate.com/windowsupdate/redist/standalone/7.6.7600.320/windowsupdateagent-7.6-x86.exe "%systemdrive%\packages\wua.exe"`

![image](https://user-images.githubusercontent.com/18270870/168497768-1cca30f8-58a5-4dbd-9530-b316aeb7d6f0.png)

Is there anything obvious that I'm missing? I'm sure there is something silly preventing CMD from completing this download that I'm not understanding...
