### ISSUE TITLE
Hi, download files

### ISSUE THREAD

**Issue by Roqelio** [aakkam22/windowsUpdateLoopFix#9]
When i try to download the files, this message comes out.
![error](https://user-images.githubusercontent.com/127787377/224812035-a8813993-3df9-476c-82af-64b126cadebf.png)

**Comment by HorlogeSkynet** [comment]
URLs are still working (on my machine). Have you tried multiple times/again lately ?

Thanks bye 👋

**Comment by PiuksPauks** [comment]
Have exactly same issue as first post described.

**Comment by aakkam22** [comment]
When it reaches the "Press any key to exit", can you check the download directory listed, C:\Packages and see if 3020369 and 3172605 are there?

**Comment by PiuksPauks** [comment]
No, they are not there. Only wsus.exe was there. Downloaded one of them kb3020369/kb3172605 manually and told its was not applicable for this system. Installed the wsus.exe and windows update worked after that.

**Comment by aakkam22** [comment]
Thanks for the update, glad you were able to figure it out. Closing this bug now.
